project:
  type: website

website:
  title: "Cutaneous Oncology Interest Group"
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "About the COIG"
        file: about_the_coig.qmd
      - text: "Journal Club"
        file: jc.qmd
      - text: "Perspectives on the Science"
        file: perspectives.qmd

  sidebar:
    - title: "About the COIG"
      style: "docked"
      background: light
      contents:
        - about_the_coig.qmd
    - title: "Perspectives on the Science"
      style: "docked"
      background: light
      contents:
        - perspectives.qmd
        - POTS_October_2022.qmd  
        - POTS_November_2022.qmd  
      

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

