project:
  type: website

website:
  title: "Cutaneous Oncology Interest Group"
  navbar:
    left:
      - href: index.qmd
        text: Perspective Pieces
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

