project:
  type: website

website:
  title: "Cutaneous Oncology Interest Group"
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "About the COIG"
        file: about_the_coig.qmd
      - text: "Perspectives on the Science"
        file: perspectives.qmd

      

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

