project:
  type: website

website:
  title: "Cutaneous Oncology Interest Group"
    # Add site-url (without trailing / at the end)
  site-url: https://cutaneousoncology.io
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    right:
      - text: "Journal of Cutaneous Oncology"
        href: joco.qmd
      - text: "COIG Journal Club"
        href: jc.qmd


    
#format:
#  html:
#    theme: 
#      light: cosmo
#      dark: slate
#    css: styles.css
#    toc: true

format:
  html:
    theme: theme.scss

editor: source

