# SoCO Journal Club — April 6, 2026
# IGNYTE attendance processor — robust UTF-16 Teams export version
#
# Expected structure:
#
# journal_club/
# └── April 6 2026 - IGNYTE/
#     ├── index.qmd
#     ├── scripts/
#     │   └── process_attendance.R
#     └── files/
#         └── meeting recap-attendance/
#             └── [Teams attendance .csv/.xls/.xlsx]
#
# Outputs:
#   files/meeting recap-attendance/attendance_clean.csv
#   files/meeting recap-attendance/attendance_summary.csv
#
# IMPORTANT:
# Microsoft Teams files with a .csv extension may actually be UTF-16LE,
# tab-delimited text. This script deliberately avoids readr/vroom delimiter
# guessing for those files and splits the UTF-16 text manually on tabs.

suppressPackageStartupMessages({
  library(tidyverse)
  library(scales)
})

if (!requireNamespace("readxl", quietly = TRUE)) {
  stop(
    "Package 'readxl' is required for Excel attendance files. ",
    "Install with install.packages('readxl')."
  )
}


# =============================================================================
# 1. Resolve meeting directory
# =============================================================================

if (!exists("meeting_dir", inherits = TRUE)) {
  
  get_script_path <- function() {
    
    # RStudio Source button
    if (
      interactive() &&
      requireNamespace("rstudioapi", quietly = TRUE)
    ) {
      
      ctx <- tryCatch(
        rstudioapi::getSourceEditorContext(),
        error = function(e) NULL
      )
      
      if (
        !is.null(ctx) &&
        !is.null(ctx$path) &&
        nzchar(ctx$path)
      ) {
        
        return(
          normalizePath(
            ctx$path,
            winslash = "/",
            mustWork = TRUE
          )
        )
      }
    }
    
    # Rscript
    args <- commandArgs(trailingOnly = FALSE)
    file_arg <- grep("^--file=", args, value = TRUE)
    
    if (length(file_arg) > 0) {
      
      return(
        normalizePath(
          sub("^--file=", "", file_arg[1]),
          winslash = "/",
          mustWork = TRUE
        )
      )
    }
    
    stop(
      paste0(
        "Could not determine the meeting directory. ",
        "Render index.qmd or source this script from RStudio."
      )
    )
  }
  
  script_path <- get_script_path()
  script_dir <- dirname(script_path)
  
  # Expected:
  # meeting_folder/scripts/process_attendance.R
  meeting_dir <- dirname(script_dir)
}

meeting_dir <- normalizePath(
  meeting_dir,
  winslash = "/",
  mustWork = TRUE
)

attendance_dir <- file.path(
  meeting_dir,
  "files",
  "meeting recap-attendance"
)

message("Meeting directory: ", meeting_dir)
message("Attendance directory: ", attendance_dir)

if (!dir.exists(attendance_dir)) {
  
  dir.create(
    attendance_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )
}


# =============================================================================
# 2. Locate Teams attendance export
# =============================================================================

attendance_candidates <- list.files(
  attendance_dir,
  pattern = "(Attendance report|attendance).*\\.(csv|xls|xlsx)$",
  full.names = TRUE,
  ignore.case = TRUE
)

# Never select files generated by this script.
attendance_candidates <- attendance_candidates[
  !tolower(basename(attendance_candidates)) %in%
    c(
      "attendance_clean.csv",
      "attendance_summary.csv"
    )
]

if (length(attendance_candidates) == 0) {
  
  stop(
    paste0(
      "No Teams attendance export found.\n",
      "Place the .csv, .xls, or .xlsx file in:\n",
      attendance_dir
    )
  )
}

attendance_file <- attendance_candidates[
  which.max(
    file.info(attendance_candidates)$mtime
  )
]

message("Using attendance file: ", attendance_file)


# =============================================================================
# 3. Helpers
# =============================================================================

duration_to_minutes <- function(x) {
  
  x <- replace_na(
    as.character(x),
    ""
  )
  
  hours <- str_extract(
    x,
    "\\d+(?=h)"
  ) |>
    replace_na("0") |>
    as.numeric()
  
  mins <- str_extract(
    x,
    "\\d+(?=m)"
  ) |>
    replace_na("0") |>
    as.numeric()
  
  secs <- str_extract(
    x,
    "\\d+(?=s)"
  ) |>
    replace_na("0") |>
    as.numeric()
  
  60 * hours + mins + secs / 60
}


credential_pattern <- paste0(
  "\\b(",
  paste(
    c(
      "MD",
      "DO",
      "PhD",
      "Ph\\.D",
      "MPH",
      "MBA",
      "MS",
      "MSc",
      "CNP",
      "NP",
      "PA-C",
      "PA",
      "RN",
      "BSN",
      "MSN",
      "FACS",
      "FAAD",
      "FACEP"
    ),
    collapse = "|"
  ),
  ")\\b\\.?"
)


clean_person_name <- function(x) {
  
  x <- x |>
    replace_na("") |>
    str_replace_all("[\u2018\u2019]", "'") |>
    str_remove_all("\\s*\\([^)]*\\)") |>
    str_remove_all("\\s*\\[[^]]*\\]") |>
    str_replace_all(
      regex(
        credential_pattern,
        ignore_case = TRUE
      ),
      ""
    ) |>
    str_replace_all("\\s+", " ") |>
    str_squish()
  
  map_chr(
    x,
    function(nm) {
      
      if (is.na(nm) || nm == "") {
        return(NA_character_)
      }
      
      pieces <- str_split(
        nm,
        ",",
        simplify = FALSE
      )[[1]] |>
        str_squish()
      
      pieces <- pieces[
        pieces != ""
      ]
      
      # Teams frequently exports names as:
      # Last, First Middle, credentials
      #
      # Credential text has already been removed above.
      if (length(pieces) >= 2) {
        
        last <- pieces[1]
        
        given <- paste(
          pieces[-1],
          collapse = " "
        )
        
        nm <- str_squish(
          paste(
            given,
            last
          )
        )
      }
      
      nm |>
        str_replace_all("\\s*,\\s*", " ") |>
        str_replace_all("\\s+", " ") |>
        str_squish()
    }
  )
}


first_last_key <- function(x) {
  
  clean <- clean_person_name(x)
  
  map_chr(
    clean,
    function(nm) {
      
      if (is.na(nm) || nm == "") {
        return(NA_character_)
      }
      
      words <- nm |>
        str_to_lower() |>
        str_replace_all(
          "[^a-z0-9' -]",
          " "
        ) |>
        str_squish() |>
        str_split(
          "\\s+",
          simplify = FALSE
        )
      
      words <- words[[1]]
      words <- words[
        words != ""
      ]
      
      if (length(words) == 0) {
        return(NA_character_)
      }
      
      if (length(words) == 1) {
        
        return(
          str_replace_all(
            words,
            "[^a-z0-9]",
            ""
          )
        )
      }
      
      paste0(
        str_replace_all(
          words[1],
          "[^a-z0-9]",
          ""
        ),
        str_replace_all(
          words[length(words)],
          "[^a-z0-9]",
          ""
        )
      )
    }
  )
}


clean_display_name <- function(x) {
  
  case_when(
    str_detect(
      str_to_lower(x),
      "vernon.*sondak"
    ) ~ "Vern Sondak",
    
    str_detect(
      str_to_lower(x),
      "sorrentino"
    ) ~ "Alex Sorrentino",
    
    str_detect(
      str_to_lower(x),
      "ken tsai"
    ) ~ "Ken Tsai",
    
    str_detect(
      str_to_lower(x),
      "^dl$"
    ) ~ "Don Lawrence",
    
    str_detect(
      str_to_lower(x),
      "oak conference room"
    ) ~ "Replimune team",
    
    TRUE ~ x
  )
}


# =============================================================================
# 4. Read Teams report
# =============================================================================

ext <- tolower(
  tools::file_ext(
    attendance_file
  )
)


if (ext %in% c("xls", "xlsx")) {
  
  # ---------------------------------------------------------------------------
  # Excel Teams export
  # ---------------------------------------------------------------------------
  
  raw <- readxl::read_excel(
    attendance_file,
    col_names = FALSE,
    col_types = "text",
    .name_repair = "minimal"
  )
  
  raw <- as_tibble(
    raw,
    .name_repair = "minimal"
  )
  
} else {
  
  # ---------------------------------------------------------------------------
  # Teams "CSV" export
  #
  # These files may actually be:
  #   * UTF-16LE
  #   * tab-delimited
  #   * variable-width by section
  #
  # readr/vroom can occasionally treat the entire line as one field.
  # We therefore read the text ourselves and split each line explicitly.
  # ---------------------------------------------------------------------------
  
  con <- file(
    attendance_file,
    open = "r",
    encoding = "UTF-16LE"
  )
  
  on.exit(
    close(con),
    add = TRUE
  )
  
  lines <- readLines(
    con,
    warn = FALSE
  )
  
  # Remove UTF BOM if it survives decoding.
  if (length(lines) > 0) {
    lines[1] <- sub(
      "^\ufeff",
      "",
      lines[1]
    )
  }
  
  split_lines <- strsplit(
    lines,
    "\t",
    fixed = TRUE
  )
  
  max_cols <- max(
    lengths(split_lines)
  )
  
  padded <- lapply(
    split_lines,
    function(x) {
      
      length(x) <- max_cols
      
      x[
        is.na(x)
      ] <- ""
      
      x
    }
  )
  
  raw <- as_tibble(
    do.call(
      rbind,
      padded
    ),
    .name_repair = "minimal"
  )
}


# Give every imported column a safe temporary name before using dplyr.
names(raw) <- paste0(
  "col_",
  seq_len(
    ncol(raw)
  )
)

# Convert every cell to clean text.
raw <- raw |>
  mutate(
    across(
      everything(),
      ~ replace_na(
        as.character(.x),
        ""
      ) |>
        str_squish()
    )
  )

message(
  "Imported rows: ",
  nrow(raw)
)

message(
  "Imported columns: ",
  ncol(raw)
)


# =============================================================================
# 5. Locate Teams sections robustly
# =============================================================================

# Search the entire row, not just the first column.
row_text <- apply(
  as.data.frame(raw),
  1,
  function(z) {
    
    paste(
      z[
        z != ""
      ],
      collapse = " | "
    ) |>
      str_squish()
  }
)


participants_section <- which(
  str_detect(
    row_text,
    regex(
      "(^|\\|\\s*)2\\.\\s*Participants\\b",
      ignore_case = TRUE
    )
  )
)[1]


activities_section <- which(
  str_detect(
    row_text,
    regex(
      "(^|\\|\\s*)3\\.\\s*In[- ]Meeting Activities\\b",
      ignore_case = TRUE
    )
  )
)[1]


if (
  is.na(participants_section) ||
  is.na(activities_section)
) {
  
  likely_rows <- which(
    str_detect(
      row_text,
      regex(
        "participant|meeting activit|duration|camera|unmute|raise",
        ignore_case = TRUE
      )
    )
  )
  
  preview <- paste(
    paste0(
      likely_rows,
      ": ",
      row_text[
        likely_rows
      ]
    ),
    collapse = "\n"
  )
  
  stop(
    paste0(
      "Could not identify the Teams participant/activity sections.\n\n",
      "Rows containing likely attendance keywords:\n",
      preview
    )
  )
}


if (activities_section <= participants_section) {
  
  stop(
    paste0(
      "Teams section order is unexpected: Participants row = ",
      participants_section,
      "; Activities row = ",
      activities_section
    )
  )
}


message(
  "Participants section row: ",
  participants_section
)

message(
  "Activities section row: ",
  activities_section
)


# =============================================================================
# 6. Locate participant header row
# =============================================================================

candidate_header_rows <- seq(
  participants_section + 1,
  activities_section - 1
)


expected_headers <- c(
  "Name",
  "First Join",
  "Last Leave",
  "In-Meeting Duration",
  "Email",
  "Participant ID",
  "Participant ID (UPN)",
  "Role",
  "Engagement: Reaction-Applause",
  "Engagement: Reaction-Laugh",
  "Engagement: Reaction-Like",
  "Engagement: Reaction-Love",
  "Engagement: Reaction-Surprised",
  "Engagement: Camera On",
  "Engagement: Raise Hands",
  "Engagement: Unmute",
  "Reactions"
)


header_scores <- map_int(
  candidate_header_rows,
  function(i) {
    
    vals <- unlist(
      raw[
        i,
        ,
        drop = FALSE
      ],
      use.names = FALSE
    ) |>
      as.character() |>
      str_squish()
    
    sum(
      vals %in% expected_headers
    )
  }
)


header_row <- candidate_header_rows[
  which.max(
    header_scores
  )
]


if (
  length(header_row) == 0 ||
  max(header_scores) < 2
) {
  
  candidate_preview <- paste(
    paste0(
      candidate_header_rows,
      ": ",
      row_text[
        candidate_header_rows
      ]
    ),
    collapse = "\n"
  )
  
  stop(
    paste0(
      "Could not identify the Teams participant header row.\n\n",
      "Candidate rows between Participants and Activities:\n",
      candidate_preview
    )
  )
}


message(
  "Participant header row: ",
  header_row
)


header <- raw[
  header_row,
  ,
  drop = FALSE
] |>
  unlist(
    use.names = FALSE
  ) |>
  as.character() |>
  str_squish()


empty_header <- is.na(header) |
  header == ""


header[
  empty_header
] <- paste0(
  "X",
  which(
    empty_header
  )
)


header <- make.unique(
  header
)


# =============================================================================
# 7. Extract participant rows
# =============================================================================

participant_rows <- seq(
  header_row + 1,
  activities_section - 1
)


participants_raw <- raw[
  participant_rows,
  ,
  drop = FALSE
]


names(
  participants_raw
) <- header


required <- c(
  "Name",
  "In-Meeting Duration",
  "Engagement: Camera On",
  "Engagement: Raise Hands",
  "Engagement: Unmute"
)


missing_required <- setdiff(
  required,
  names(
    participants_raw
  )
)


if (length(missing_required) > 0) {
  
  stop(
    paste0(
      "Missing expected Teams columns: ",
      paste(
        missing_required,
        collapse = ", "
      ),
      "\n\nColumns actually found:\n",
      paste(
        names(
          participants_raw
        ),
        collapse = " | "
      )
    )
  )
}


# =============================================================================
# 8. Clean participant records
# =============================================================================

participants <- participants_raw |>
  transmute(
    name_raw = as.character(
      Name
    ),
    
    Name = clean_display_name(
      clean_person_name(
        Name
      )
    ),
    
    match_key = first_last_key(
      Name
    ),
    
    duration_min = duration_to_minutes(
      `In-Meeting Duration`
    ),
    
    camera_on = suppressWarnings(
      as.numeric(
        `Engagement: Camera On`
      )
    ) |>
      replace_na(0),
    
    hand_raise = suppressWarnings(
      as.numeric(
        `Engagement: Raise Hands`
      )
    ) |>
      replace_na(0),
    
    unmute = suppressWarnings(
      as.numeric(
        `Engagement: Unmute`
      )
    ) |>
      replace_na(0)
  ) |>
  filter(
    !is.na(Name),
    Name != "",
    
    !str_detect(
      Name,
      regex(
        "read\\.ai|meeting notes|notetaker|otter",
        ignore_case = TRUE
      )
    )
  )


# =============================================================================
# 9. Reconcile reconnects
# =============================================================================

people <- participants |>
  group_by(
    match_key
  ) |>
  summarise(
    Name = first(
      Name
    ),
    
    duration_min = sum(
      duration_min,
      na.rm = TRUE
    ),
    
    camera_on = sum(
      camera_on,
      na.rm = TRUE
    ),
    
    hand_raise = sum(
      hand_raise,
      na.rm = TRUE
    ),
    
    unmute = sum(
      unmute,
      na.rm = TRUE
    ),
    
    .groups = "drop"
  ) |>
  mutate(
    is_room = str_detect(
      Name,
      regex(
        "conference room|meeting room",
        ignore_case = TRUE
      )
    ),
    
    any_camera = camera_on > 0,
    any_hand_raise = hand_raise > 0,
    any_unmute = unmute > 0
  ) |>
  arrange(
    Name
  )


# =============================================================================
# 10. Meeting summary
# =============================================================================

headline <- people |>
  summarise(
    connections = n(),
    
    room_connections = sum(
      is_room,
      na.rm = TRUE
    ),
    
    median_minutes = median(
      duration_min,
      na.rm = TRUE
    ),
    
    pct_60min_plus = mean(
      duration_min >= 60,
      na.rm = TRUE
    ),
    
    pct_camera = mean(
      any_camera,
      na.rm = TRUE
    ),
    
    pct_unmute = mean(
      any_unmute,
      na.rm = TRUE
    ),
    
    pct_hand_raise = mean(
      any_hand_raise,
      na.rm = TRUE
    )
  )


# =============================================================================
# 11. Save outputs
# =============================================================================

clean_path <- file.path(
  attendance_dir,
  "attendance_clean.csv"
)


summary_path <- file.path(
  attendance_dir,
  "attendance_summary.csv"
)


readr::write_csv(
  people,
  clean_path
)


readr::write_csv(
  headline,
  summary_path
)


# =============================================================================
# 12. Console summary
# =============================================================================

message("")
message(
  "Attendance processing complete."
)

message(
  "Unique Teams connections: ",
  headline$connections
)

message(
  "Conference-room connections: ",
  headline$room_connections
)

message(
  "Median minutes: ",
  round(
    headline$median_minutes,
    1
  )
)

message(
  "Stayed >=60 min: ",
  scales::percent(
    headline$pct_60min_plus,
    accuracy = 1
  )
)

message(
  "Camera on: ",
  scales::percent(
    headline$pct_camera,
    accuracy = 1
  )
)

message(
  "Unmuted: ",
  scales::percent(
    headline$pct_unmute,
    accuracy = 1
  )
)

message(
  "Raised hand: ",
  scales::percent(
    headline$pct_hand_raise,
    accuracy = 1
  )
)

message("")
message("Wrote:")
message("  ", clean_path)
message("  ", summary_path)
